# Generated by Django 3.2.7 on 2021-10-01 02:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('appName1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='instructorcourses',
        ),
        migrations.RemoveField(
            model_name='details',
            name='specialcourses',
        ),
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 1, 2, 42, 12, 80521, tzinfo=utc), verbose_name='started from'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='coursetype',
            field=models.CharField(default=datetime.datetime(2021, 10, 1, 2, 42, 59, 566801, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='yourchoice',
            field=models.BooleanField(default=False),
        ),
    ]
