# Generated by Django 3.2.7 on 2021-11-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appName1', '0004_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourses',
            name='coursename',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='allcourses',
            name='instructorname',
            field=models.CharField(max_length=500),
        ),
    ]
